version: '3.8'

# Use postgres/example user/password credentials
services:

  db-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: test1
      POSTGRES_DB: knowledge
      TZ: America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    restart: always

  db-mongo:
    image: mongo:latest
    volumes:
      - ./.docker/mongo/data:/data/db
    ports:
      - "27017:27017"
    environment:
      TZ: America/Sao_Paulo
      MONGODB_DATABASE: knowledge
    restart: always